"""AI-assisted mining tools."""

from .assumptions import (
    ASSUMPTION_TEMPLATE,
    AssumptionResult,
    build_assumption_hook,
    generate_edge_assumptions,
)
from .credibility import (
    CLAIM_CREDIBILITY_TEMPLATE,
    ClaimCredibilityResult,
    EvidenceScore,
    build_claim_credibility_hook,
    score_claims_with_llm,
)
from .evaluation import (
    EdgeValidationResult,
    EvidenceEvaluation,
    HeuristicEvaluator,
    score_evidence,
    validate_edges,
)
from .llm import (
    AnthropicClient,
    AsyncLLMClient,
    AsyncLLMHook,
    AsyncNoOpLLMClient,
    LLMClient,
    LLMHook,
    NoOpLLMClient,
    OllamaClient,
    OpenAIClient,
    PromptTemplate,
)
from .miner import (
    ArgumentMiner,
    AsyncArgumentMiner,
    AsyncArgumentMinerAdapter,
    AsyncLongDocumentMiner,
    HookedArgumentMiner,
    LongDocumentMiner,
    Segmenter,
    SimpleArgumentMiner,
)
from .mining import (
    FixedWindowSplitter,
    GraphReconciler,
    MergePolicy,
    MergeResult,
    ParagraphSplitter,
    Segment,
    SimpleGraphReconciler,
    Splitter,
    token_jaccard_similarity,
)

__all__ = [
    "ArgumentMiner",
    "AsyncArgumentMiner",
    "AsyncArgumentMinerAdapter",
    "AsyncLLMClient",
    "AsyncLLMHook",
    "AsyncNoOpLLMClient",
    "AnthropicClient",
    "AsyncLongDocumentMiner",
    "ASSUMPTION_TEMPLATE",
    "CLAIM_CREDIBILITY_TEMPLATE",
    "AssumptionResult",
    "ClaimCredibilityResult",
    "EdgeValidationResult",
    "EvidenceScore",
    "EvidenceEvaluation",
    "HeuristicEvaluator",
    "HookedArgumentMiner",
    "LLMClient",
    "LLMHook",
    "FixedWindowSplitter",
    "GraphReconciler",
    "LongDocumentMiner",
    "MergePolicy",
    "MergeResult",
    "NoOpLLMClient",
    "OllamaClient",
    "OpenAIClient",
    "ParagraphSplitter",
    "PromptTemplate",
    "Segment",
    "Segmenter",
    "SimpleArgumentMiner",
    "SimpleGraphReconciler",
    "Splitter",
    "token_jaccard_similarity",
    "build_assumption_hook",
    "score_evidence",
    "score_claims_with_llm",
    "generate_edge_assumptions",
    "validate_edges",
    "build_claim_credibility_hook",
]
