"""AI-assisted mining tools."""

from .evaluation import (
    EdgeValidationResult,
    EvidenceEvaluation,
    HeuristicEvaluator,
    score_evidence,
    validate_edges,
)
from .llm import (
    AsyncLLMClient,
    AsyncLLMHook,
    AsyncNoOpLLMClient,
    LLMClient,
    LLMHook,
    NoOpLLMClient,
    OllamaClient,
    PromptTemplate,
)
from .miner import (
    ArgumentMiner,
    AsyncArgumentMiner,
    AsyncArgumentMinerAdapter,
    AsyncLongDocumentMiner,
    HookedArgumentMiner,
    LongDocumentMiner,
    Segmenter,
    SimpleArgumentMiner,
)
from .mining import (
    FixedWindowSplitter,
    GraphReconciler,
    MergePolicy,
    MergeResult,
    ParagraphSplitter,
    Segment,
    SimpleGraphReconciler,
    Splitter,
    token_jaccard_similarity,
)

__all__ = [
    "ArgumentMiner",
    "AsyncArgumentMiner",
    "AsyncArgumentMinerAdapter",
    "AsyncLLMClient",
    "AsyncLLMHook",
    "AsyncNoOpLLMClient",
    "AsyncLongDocumentMiner",
    "EdgeValidationResult",
    "EvidenceEvaluation",
    "HeuristicEvaluator",
    "HookedArgumentMiner",
    "LLMClient",
    "LLMHook",
    "FixedWindowSplitter",
    "GraphReconciler",
    "LongDocumentMiner",
    "MergePolicy",
    "MergeResult",
    "NoOpLLMClient",
    "OllamaClient",
    "ParagraphSplitter",
    "PromptTemplate",
    "Segment",
    "Segmenter",
    "SimpleArgumentMiner",
    "SimpleGraphReconciler",
    "Splitter",
    "token_jaccard_similarity",
    "score_evidence",
    "validate_edges",
]
